@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!theme cerulean-outline

Boundary(t1, "Trust Zone Bob") {
    Container(pki1, "PKI Bob", "Public Key Infrastructure", "Manages certificates in zone")
    Container(p1, "Contract Provider", "", "Provides participating contracts")
    Container(app, "API", "", "Returns a list of Star Wars characters")
    Container(envoyApp, "API Proxy", "Envoy")
    Container(translatorApp, "API Translator", "WirePact Translator")
}

BiRel(envoyApp, translatorApp, "external authentication", "gRPC", "Extracts and translates the WirePact identity from the JWT and provides correct authentication information")
Rel_R(envoyApp, app, "Forwards call after authentication")
Rel_L(translatorApp, pki1, "Requests certificate")
Rel_R(p1, envoyApp, "Key Material", "", "Provides key material and certificate chain for all interzonal communication")
Rel_D(p1, pki1, "Requests certificate")

@enduml