@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!theme cerulean-outline

Person(admin, "Admin")

System(repo, "Contract Repository", "Manages the contracts between trust zones")

Boundary(t1, "Trust Zone 1") {
    Container(pki1, "Public Key Infrastructure", "PKI", "Manages certificates in zone")
    Container(p1, "Contract Provider", "", "Provides participating contracts")
}

Boundary(t2, "Trust Zone 2") {
    Container(pki2, "Public Key Infrastructure", "PKI", "Manages certificates in zone")
    Container(p2, "Contract Provider", "", "Provides participating contracts")
}

Rel(admin, repo, "Administers the repository")

Rel(p1, repo, "Fetches contracts")
Rel(p2, repo, "Fetches contracts")
Rel(pki1, repo, "Contains info in contract")
Rel(pki2, repo, "Contains info in contract")

@enduml