name: Publish GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Document
        uses: docker://ghcr.io/buehler/mse-pandoc:latest
        with:
          args: make pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: public

  deploy-gh-pages:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        id: download
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - run: mkdir -p public/ && mv artifacts/pdf/* public/
      - name: Deploy gh pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          BRANCH: gh-pages
          FOLDER: public
